enum Gender {
    Male = 'male',
    Female = 'female',
}

export const Alums = [
    {
        name: 'Yash Saraswat',
        designation_a: 'Senior Protocol Engineer at Aleph Finance ',
        image: '/team_images/panic.png',
        github: 'https://github.com/0xpanicError/',
        twitter: 'https://twitter.com/0xpanicError/',
        linkedin: 'https://www.linkedin.com/in/yash2399/',
        gender: Gender.Male,
    },
    {
        name: 'Aditya Gupta',
        designation_a: 'Ethereum protocol fellow',
        image: '/team_images/aditya.jpg',
        github: 'https://github.com/1010adigupta/',
        twitter: 'https://x.com/darex_1010/',
        linkedin: 'https://www.linkedin.com/in/aditya-gupta-905a61239/',
        gender: Gender.Male
    },
    {
        name: 'Samaredra Gouda',
        designation_a: 'Dev at Instadapp',
        image: '/team_images/samarendra_.jpg',
        github: 'https://github.com/SamarendraGouda/',
        twitter: 'https://x.com/0xSamarendra/',
        linkedin: 'https://www.linkedin.com/in/samarendra-gouda/',
        gender: Gender.Male
    },
    {
        name: 'Prabhat Verma',
        designation_a: 'Rust Engineer at Galoy',
        image: '/team_images/prabhat.jpg',
        github: 'https://github.com/Prabhat1308/',
        twitter: 'https://x.com/pr0b0t1sc00l/',
        linkedin: 'https://www.linkedin.com/in/prabhat-verma-7ab615206/',
        gender: Gender.Male
    },
        {
        name: 'Varun Sharma',
        designation_a: 'Watson at Sherlock',
        image: '/team_images/varun.jpg',
        github: 'https://www.linkedin.com/in/vsharma4394/',
        twitter: '',
        linkedin: '',
        gender: Gender.Male
    },
    {
        name: 'Naman Harwani',
        designation_a: 'Designer',
        image: '/team_images/naman.jpg',
        github: 'https://github.com/burgerdrummer/',
        twitter: 'https://twitter.com/BurgerDrummer/',
        linkedin: 'https://www.linkedin.com/in/namaha/',
        gender: Gender.Male
    },
    {
        name: 'Barun Sethi',
        designation_a: 'Product Designer at Yulu',
        image: '/team_images/barun.jpg',
        github: '',
        twitter: '',
        linkedin: 'https://www.linkedin.com/in/barun-design/',
        gender: Gender.Male
    },
    {
        name: 'Vaishnavi Singh',
        designation_a: 'Core Member',
        image: '/team_images/vaishnavi.jpg',
        github: 'https://github.com/07Vaishnavi_Singh/',
        twitter: 'https://x.com/Vaiz_07/',
        linkedin: 'https://www.linkedin.com/in/vaishnavi-singh-3a104b204/',
        gender: Gender.Female
    },
    {
        name: 'Sumit Kumar',
        designation_a: 'Dev at neobase',
        image: '/team_images/sumit.jpg',
        github: 'https://github.com/startup-dreamer/',
        twitter: 'https://x.com/Startup_dmr/',
        linkedin: 'https://www.linkedin.com/in/startup1dreamer/',
        gender: Gender.Male
    },
    {
        name: 'Shivam Verma',
        designation_a: 'Core Member',
        designation_b: 'Unfold finalist',
        image: '/team_images/shivam.jpg',
        github: 'https://github.com/ShivamPoW/',
        twitter: 'https://x.com/Shevxer/',
        linkedin: 'https://www.linkedin.com/in/shivampow/',
        gender: Gender.Male
    },
    {
        name: 'Omkar Darde',
        designation_a: 'Designer',
        designation_b: 'Unfold finalist',
        image: '/team_images/omkar.jpg',
        github: 'https://github.com/0xClint/',
        twitter: 'https://x.com/0x_Clint/',
        linkedin: 'https://www.linkedin.com/in/omkardarde/',
        gender: Gender.Male
    },
    {
        name: 'Alok Kumar',
        designation_a: 'Core Member',
        image: '/team_images/alok.jpg',
        github: 'https://github.com/surfer05/',
        twitter: 'https://x.com/surfer__05/',
        linkedin: 'https://www.linkedin.com/in/alok-kumar-089967220/',
        gender: Gender.Male
    },
    {
        name: 'Priyanshu Mehra',
        designation_a: 'Head of Design',
        image: '/team_images/priyanshu.jpg',
        github: 'https://github.com/Priyanshu95663/',
        twitter: 'https://x.com/Priynshu_M03/',
        linkedin: 'https://www.linkedin.com/in/priyanshum4design/',
        gender: Gender.Male
    },
    {
        name: 'Archit Gangwal',
        designation_a: 'Core Member',
        image: '/team_images/archit.jpeg',
        github: 'https://github.com/arcwood/',
        twitter: '',
        linkedin: 'https://www.linkedin.com/in/archit-gangwal-16b035228/',
        gender: Gender.Male
    },
    {
        name: 'Shashank Trivedi',
        designation_a: 'Core Member',
        image: '/team_images/shashank.jpg',
        github: 'https://github.com/lordshashank/',
        twitter: 'https://x.com/0xlord_forever/',
        linkedin: 'https://www.linkedin.com/in/shashanktrivedi7/',
        gender: Gender.Male
    },
    {
        name: 'Puspendra',
        designation_a: 'Core Member',
        image: '/team_images/puspendra.jpg',
        github: 'https://github.com/silent-cipher/',
        twitter: 'https://x.com/silent_c1pher/',
        linkedin: 'https://www.linkedin.com/in/puspendra-mahariya-112059238/',
        gender: Gender.Male
    },
    {
        name: 'Richa',
        designation_a: 'Software Developer, JP Morgan & Chase',
        image: '/team_images/richa.jpg',
        github: 'https://github.com/Richa-iitr/',
        twitter: 'https://x.com/richa3112/',
        linkedin: 'https://www.linkedin.com/in/richa-3087a120a/',
        gender: Gender.Female,
    },
    {
        name: 'Chirag Baghasingh',
        designation_a: 'Ethereum Protocol Fellow',
        image: '/team_images/chirag.jpg',
        github: 'https://github.com/chirag-bgh/',
        twitter: 'https://x.com/0xstrider_/',
        linkedin: 'https://www.linkedin.com/in/chirag-baghasingh-753b711b9/',
        gender: Gender.Male,
    },
    {
        name: 'Movish Verma',
        designation_a: 'Software Developer, SAP Labs',
        image: '/team_images/movish.jpg',
        github: '',
        twitter: 'https://x.com/movish_v/',
        linkedin: 'https://www.linkedin.com/in/movishverma/',
        gender: Gender.Male,
    },
    {
        name: 'Neerav Chittora',
        designation_a: 'Software Developer, Google',
        image: '/team_images/neerav.jpeg',
        github: 'https://github.com/neerav1234/',
        twitter: 'https://x.com/NeeravChittora/',
        linkedin: 'https://www.linkedin.com/in/neerav-chittora-a470071ba/',
        gender: Gender.Male,
    },
    {
        name: 'Pooja Patel',
        designation_a: 'Software Developer, Microsoft',
        image: '/team_images/pooja.jpg',
        github: '',
        twitter: 'https://x.com/0xpooja6/',
        linkedin: 'https://www.linkedin.com/in/pooja-patel-512b29227/',
        gender: Gender.Female,
    },
    {
        name: 'Parthsarthi Mishra',
        designation_a: 'Software Engineer, Qualcomm',
        image: '/team_images/parthsarthi.jpg',
        github: '',
        twitter: '',
        linkedin: 'https://www.linkedin.com/in/parthsarthi-mishra-86a30814b/',
        gender: Gender.Male,
    },
    {
        name: 'Kamal Sharma',
        designation_a: '',
        image: '/team_images/kamal.jpg',
        github: 'https://github.com/kamal3951/',
        twitter: 'https://x.com/0xmaxlad/',
        linkedin: 'https://www.linkedin.com/in/kamalsharma01/',
        gender: Gender.Male,
    },
    {
        name: 'Yash Bhanushali',
        designation_a: '',
        image: '/team_images/yash.jpg',
        github: '',
        twitter: 'https://x.com/Y_ash19/',
        linkedin: 'https://www.linkedin.com/in/yash-bhanushali-a34a2a22a/',
        gender: Gender.Male,
    },
    {
        name: 'Jatin Agarwal',
        designation_a: '',
        image: '/team_images/jatin.jpg',
        github: '',
        twitter: 'https://x.com/_jatinagarwal/',
        linkedin: 'https://www.linkedin.com/in/jatinagarwal69/',
        gender: Gender.Male,
    },
]
